proxy-groups:
  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - DIRECT
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ”¯ æ•…éšœè½¬ç§»
      - ğŸ”® è´Ÿè½½å‡è¡¡
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
  - name: ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
    type: select
    include-all: true
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    interval: 300
    tolerance: 50
    include-all: true
  - name: ğŸ”¯ æ•…éšœè½¬ç§»
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    include-all: true
  - name: ğŸ”® è´Ÿè½½å‡è¡¡
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    include-all: true
  - name: âœ¨ éå¤§é™†èŠ‚ç‚¹
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    include-all: true
    exclude-filter: (?i)ä¸­|é¦™|CN|cn|HK|hk
  - name: ğŸ’¬ OpenAi
    type: select
    proxies:
      - âœ¨ éå¤§é™†èŠ‚ç‚¹
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
  - name: ğŸ˜Š ç¼–ç¨‹ä¾èµ–
    type: select
    proxies:
      - âœ¨ éå¤§é™†èŠ‚ç‚¹
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
  - name: ğŸ“² ç”µæŠ¥æ¶ˆæ¯
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: ğŸ“¹ æ²¹ç®¡è§†é¢‘
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: ğŸ¥ å¥ˆé£è§†é¢‘
    type: select
    proxies:
      - ğŸ¥ å¥ˆé£èŠ‚ç‚¹
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: ğŸŒ å›½å¤–åª’ä½“
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: ğŸŒ å›½å†…åª’ä½“
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ“¢ è°·æ­ŒFCM
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: â“‚ï¸ å¾®è½¯äº‘ç›˜
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: â“‚ï¸ å¾®è½¯æœåŠ¡
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: ğŸ è‹¹æœæœåŠ¡
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: ğŸ® æ¸¸æˆå¹³å°
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: ğŸ¶ ç½‘æ˜“éŸ³ä¹
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ¯ å…¨çƒç›´è¿
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸƒ åº”ç”¨å‡€åŒ–
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
  - name: ğŸ¥ å¥ˆé£èŠ‚ç‚¹
    include-all: true
    filter: (?i)NF|å¥ˆé£|è§£é”|Netflix|NETFLIX|Media
    type: select
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    include-all: true
    filter: (?i)æ¸¯|HK|hk|Hong Kong|HongKong|hongkong
    type: url-test
    interval: 300
    tolerance: 50
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    include-all: true
    filter: (?i)æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan
    type: url-test
    interval: 300
    tolerance: 50
  - name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
    include-all: true
    filter: (?i)ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States
    type: url-test
    interval: 300
    tolerance: 50
  - name: ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
    include-all: true
    filter: (?i)å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan
    type: url-test
    interval: 300
    tolerance: 50
  - name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
    include-all: true
    filter: (?i)æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore
    type: url-test
    interval: 300
    tolerance: 50
  - name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
    include-all: true
    filter: (?i)KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“
    type: url-test
    interval: 300
    tolerance: 50
rule-providers:
  LocalAreaNetwork:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/LocalAreaNetwork.list
    path: ./ruleset/LocalAreaNetwork.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ai:
    url: https://testingcf.jsdelivr.net/gh/JustTestCode/somesh@master/other/ai.list
    path: ./ruleset/ai.yaml
    behavior: classical
    interval: 86400
    format: text
    type: http
  Github:
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Github.list
    path: ./ruleset/Github.yaml
    behavior: classical
    interval: 86400
    format: text
    type: http
  UnBan:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/UnBan.list
    path: ./ruleset/UnBan.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  BanAD:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanAD.list
    path: ./ruleset/BanAD.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  BanProgramAD:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanProgramAD.list
    path: ./ruleset/BanProgramAD.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  GoogleFCM:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/GoogleFCM.list
    path: ./ruleset/GoogleFCM.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  GoogleCN:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/GoogleCN.list
    path: ./ruleset/GoogleCN.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  SteamCN:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/SteamCN.list
    path: ./ruleset/SteamCN.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Bing:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Bing.list
    path: ./ruleset/Bing.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  OneDrive:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/OneDrive.list
    path: ./ruleset/OneDrive.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Microsoft:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Microsoft.list
    path: ./ruleset/Microsoft.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Apple:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Apple.list
    path: ./ruleset/Apple.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Telegram:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Telegram.list
    path: ./ruleset/Telegram.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  OpenAi:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/OpenAi.list
    path: ./ruleset/OpenAi.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  NetEaseMusic:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/NetEaseMusic.list
    path: ./ruleset/NetEaseMusic.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Epic:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Epic.list
    path: ./ruleset/Epic.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Origin:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Origin.list
    path: ./ruleset/Origin.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Sony:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Sony.list
    path: ./ruleset/Sony.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Steam:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Steam.list
    path: ./ruleset/Steam.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Nintendo:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Nintendo.list
    path: ./ruleset/Nintendo.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  YouTube:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/YouTube.list
    path: ./ruleset/YouTube.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Netflix:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Netflix.list
    path: ./ruleset/Netflix.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Bahamut:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Bahamut.list
    path: ./ruleset/Bahamut.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  BilibiliHMT:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/BilibiliHMT.list
    path: ./ruleset/BilibiliHMT.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Bilibili:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/Bilibili.list
    path: ./ruleset/Bilibili.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ChinaMedia:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaMedia.list
    path: ./ruleset/ChinaMedia.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ProxyMedia:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ProxyMedia.list
    path: ./ruleset/ProxyMedia.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ProxyGFWlist:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ProxyGFWlist.list
    path: ./ruleset/ProxyGFWlist.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ChinaDomain:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaDomain.list
    path: ./ruleset/ChinaDomain.list
    behavior: domain
    interval: 86400
    format: text
    type: http
  ChinaCompanyIp:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaCompanyIp.list
    path: ./ruleset/ChinaCompanyIp.list
    behavior: ipcidr
    interval: 86400
    format: text
    type: http
  Download:
    url: https://testingcf.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Download.list
    path: ./ruleset/Download.list
    behavior: classical
    interval: 86400
    format: text
    type: http

rules:
  - RULE-SET,LocalAreaNetwork,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,UnBan,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,ai,ğŸ’¬ OpenAi
  - RULE-SET,Github,ğŸ˜Š ç¼–ç¨‹ä¾èµ–
  - RULE-SET,BanAD,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,BanProgramAD,ğŸƒ åº”ç”¨å‡€åŒ–
  - RULE-SET,GoogleFCM,ğŸ“¢ è°·æ­ŒFCM
  - RULE-SET,GoogleCN,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,SteamCN,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,OneDrive,â“‚ï¸ å¾®è½¯äº‘ç›˜
  - RULE-SET,Microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,Apple,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,Telegram,ğŸ“² ç”µæŠ¥æ¶ˆæ¯
  - RULE-SET,NetEaseMusic,ğŸ¶ ç½‘æ˜“éŸ³ä¹
  - RULE-SET,Epic,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Origin,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Sony,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Steam,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Nintendo,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,YouTube,ğŸ“¹ æ²¹ç®¡è§†é¢‘
  - RULE-SET,Netflix,ğŸ¥ å¥ˆé£è§†é¢‘
  - RULE-SET,ChinaMedia,ğŸŒ å›½å†…åª’ä½“
  - RULE-SET,ProxyMedia,ğŸŒ å›½å¤–åª’ä½“
  - RULE-SET,ProxyGFWlist,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,ChinaDomain,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,ChinaCompanyIp,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Download,ğŸ¯ å…¨çƒç›´è¿
  - GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
